# Project sorting configuration

# part 1: general
dry_run: true
root_paths:
  - ~/work/projects
  - ~/work/archive
  - ~/work/experiments

# Date formatting
date_format:
  use_relative_dates: true
  short_format: true

  # Only used if use_relative_dates disabled  Use relative dates for dates within a week
#  use_relative_for_recent: true
#  recent_threshold_days: 7

# part 2: manual sorting

ignore:
  - python-o365
  - isnimschikov-bot-template
actual:
  - calmlib
  - dev-env
  - botspot
  # - calmmage
  # - calmmage-private
archive:
  - siri-ask-gpt
  - calmapp
  - new-bot-lib
experiments:
  - taskzilla-cm

# secondary groups
cool:
  - fedor-bot-idea
  - video-to-audio-bot
  - generate-dir-link
  - gpt-chatbot-that-stays-on-point
templates:
  - base-template
#   - typescript-project-template
  - python-project-template
  - seasonal-dir-template
  - bot-lib-bot-template
