username: petr
email: petr@superlinear.com
computer_name: "Petr's MacBook Pro"
host_name: petrs-macbook-pro
local_host_name: petrs-macbook-pro

dock:
  settings:
    # Visual settings
    autohide: true
    magnification: true
    magnification_size: 128
    tile_size: 36
    position: "bottom"  # Can be "bottom", "left", or "right"
    
    # Behavior settings
    expose_group_by_app: true
    minimize_to_application: true
    show_recent_apps: false
    show_process_indicators: true

  apps:
    - /Applications/Raycast.app
    # - /Applications/Slack.app
    - /System/Applications/System Settings.app
    # - /Applications/Warp.app
    # - /Applications/Visual Studio Code.app
    # - /Applications/PyCharm.app
    # - /Applications/Google Chrome.app