username: petrlavrov
email: petr.b.lavrov@gmail.com
computer_name: "Petr's MacBook Pro 2"
host_name: petrs-macbook-pro-2
local_host_name: petrs-macbook-pro-2

dock:
  settings:
    # Visual settings
    autohide: true
    magnification: true
    magnification_size: 128
    tile_size: 36
    position: "bottom"  # Can be "bottom", "left", or "right"
    
    # Behavior settings
    expose_group_by_app: true
    minimize_to_application: true
    show_recent_apps: false
    show_process_indicators: true

  apps:
    - /Applications/Raycast.app
    # - /Applications/Slack.app
    - /System/Applications/System Settings.app
    # - /Applications/Warp.app
    # - /Applications/Visual Studio Code.app
    # - /Applications/PyCharm.app
    # - /Applications/Google Chrome.app

homebrew:
  brews:
    - poetry
    - ripgrep
    - sonar-scanner

  casks:
    # Development
    - docker  # docker desktop app
    - jetbrains-toolbox
    - pycharm
    # - sourcetree
    - github # github desktop app
    - launchcontrol
    - warp
    # - mitmproxy
    - cursor
    - karabiner-elements
    - sublime-text
    
    # Browsers & Communication
    - google-chrome
    - slack 
    - telegram

    # Productivity & Utils
    - raycast
    - rectangle # window manager
    # - dropbox
    - obsidian
    - notion
    - chatgpt
    # - shottr # Alternative: CleanShot X - installed through setapp
    # - bartender # through setapp

    # App marketplace
    - setapp
    # todo: add instructions for user to install apps manually
    # paste
    # cleanshotX
    # bartender
    # popclip
    # hazeover

    # Creative
    - adobe-creative-cloud
    ];