# Project Manager Configuration

targets:
  new_project:
    destination: "experiments"
    
  new_mini_project:
    private_destination: "calmmage-private"
    public_destination: "calmmage"
    
  new_feature:
    subfolder: "dev/draft"  # relative to project root
    
  new_todo:
    subfolder: "dev"        # relative to project root
    filename_template: "todo_%d_%b.md"  # e.g. todo_17_Nov.md

settings:
  default_editor: "cursor"
