# Project sorting configuration

# part 1: general
dry_run: true
root_paths:
  - ~/work/projects
  - ~/work/archive
  - ~/work/experiments


# part 2: manual sorting

# skip these projects
ignored_projects:
  - base-template
  - typescript-project-template
  - python-project-template
  - seasonal-dir-template
  - foam-template
  - teletalk-template
  - bot-template
  - bot-lib-bot-template

main_projects:
  - calmmage
  - calmlib
  - bot-lib
  - taskzilla-cm
  - FastUI
  - lessmore
